blank_issues_enabled: true
contact_links:
  - name: Any questions? Help needed?
    url: https://github.com/icepcp/PythonProjects/discussions/new
    about: Create a new discussion and categorize it as Q&A.
